
#ask user to input the userId

#Convert all output to csv is the only way to work with each individual object here 
$AllAttributes = @(
     "mail",
     "officeLocation",
     "surname",
     "displayName",
     "jobTitle",
     "preferredLanguage",
     "mobilePhone",
     "givenName",
     "id",
     "userPrincipalName",
     "businessPhones",
     "ObjectId",
     "UserState",
     "UserStateChangedOn",
     "Mobile",
     "DeletionTimestamp",
     "DirSyncEnabled",
     "ImmutableId",
     "LastDirSyncTime",
     "ProvisioningErrors",
     "TelephoneNumber",
     "AboutMe",
     "AccountEnabled",
     "Activities",
     "AgeGroup",
     "AgreementAcceptances",
     "AppRoleAssignments",
     "AssignedLicenses",
     "AssignedPlans",
     "Authentication",
     "AuthorizationInfo",
     "Birthday",
     "Calendar",
     "CalendarGroups",
     "CalendarView",
     "Calendars",
     "Chats",
     "City",
     "CloudClipboard",
     "CompanyName",
     "ConsentProvidedForMinor",
     "ContactFolders",
     "Contacts",
     "Country",
     "CreatedDateTime",
     "CreatedObjects",
     "CreationType",
     "CustomSecurityAttributes",
     "DeletedDateTime",
     "Department",
     "DeviceEnrollmentLimit",
     "DeviceManagementTroubleshootingEvents",
     "DirectReports",
     "Drive",
     "Drives",
     "EmployeeExperience",
     "EmployeeHireDate",
     "EmployeeId",
     "EmployeeLeaveDateTime",
     "EmployeeOrgData",
     "EmployeeType",
     "Events",
     "Extensions",
     "ExternalUserState",
     "ExternalUserStateChangeDateTime",
     "FaxNumber",
     "FollowedSites",
     "HireDate",
     "Identities",
     "ImAddresses",
     "InferenceClassification",
     "Insights",
     "Interests",
     "IsManagementRestricted",
     "IsResourceAccount",
     "JoinedTeams",
     "LastPasswordChangeDateTime",
     "LegalAgeGroupClassification",
     "LicenseAssignmentStates",
     "LicenseDetails",
     "MailFolders",
     "MailNickname",
     "MailboxSettings",
     "ManagedAppRegistrations",
     "ManagedDevices",
     "Manager",
     "MemberOf",
     "Messages",
     "MySite",
     "Oauth2PermissionGrants",
     "OnPremisesDistinguishedName",
     "OnPremisesDomainName",
     "OnPremisesExtensionAttributes",
     "OnPremisesImmutableId",
     "OnPremisesLastSyncDateTime",
     "OnPremisesProvisioningErrors",
     "OnPremisesSamAccountName",
     "OnPremisesSecurityIdentifier",
     "OnPremisesSyncEnabled",
     "OnPremisesUserPrincipalName",
     "Onenote",
     "OnlineMeetings",
     "OtherMails",
     "Outlook",
     "OwnedDevices",
     "OwnedObjects",
     "PasswordPolicies",
     "PasswordProfile",
     "PastProjects",
     "People",
     "PermissionGrants",
     "Photo",
     "Photos",
     "Planner",
     "PostalCode",
     "PreferredDataLocation",
     "PreferredName",
     "Presence",
     "Print",
     "ProvisionedPlans",
     "ProxyAddresses",
     "RegisteredDevices",
     "Responsibilities",
     "Schools",
     "ScopedRoleMemberOf",
     "SecurityIdentifier",
     "ServiceProvisioningErrors",
     "Settings",
     "ShowInAddressList",
     "SignInActivity",
     "SignInSessionsValidFromDateTime",
     "Skills",
     "Solutions",
     "Sponsors",
     "State",
     "StreetAddress",
     "Teamwork",
     "Todo",
     "TransitiveMemberOf",
     "UsageLocation",
     "UserType",
     "AdditionalProperties"
 )

#get all the users attributes 
 #$UserAttributes = Get-EntraUser -UserId "219579df-5349-451b-9593-efcdcb25056e" -Property * | Format-List
 
 #loop through and grab each attribute 
 
     
     foreach($Prop in $AllAttributes){
          Get-EntraUser -UserId "b769f322-0a55-4c19-a5d0-fda01de85653" -Property $Prop | Select-Object -ExpandProperty $Prop
      } 




